-- Generated by Oracle SQL Developer Data Modeler 18.2.0.179.0756
--   at:        2021-11-11 20:16:54 EET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE customer (
    customer_id     INTEGER NOT NULL,
    customer_name   VARCHAR2(100),
    phone_number    VARCHAR2(100),
    ticket_limit    INTEGER
);

ALTER TABLE customer ADD CONSTRAINT customer_pk PRIMARY KEY ( customer_id );

CREATE TABLE distributor (
    distributor_id   INTEGER NOT NULL,
    name_d           VARCHAR2(100),
    phone_number_d   VARCHAR2(10),
    fee_o            NUMBER,
    rating           NUMBER,
    username_d       VARCHAR2(100),
    password_d       INTEGER
);

ALTER TABLE distributor ADD CONSTRAINT distributor_pk PRIMARY KEY ( distributor_id );

CREATE TABLE form (
    sold_tickets                 INTEGER,
    price_ticket                 INTEGER,
    ticket_type                  VARCHAR2(100),
    customer_customer_id         INTEGER NOT NULL,
    place_id                     INTEGER NOT NULL,
    distributor_distributor_id   INTEGER NOT NULL,
    show_show_id                 INTEGER NOT NULL
);

CREATE TABLE location_show (
    location_id   INTEGER NOT NULL,
    location      VARCHAR2(100),
    max_places    INTEGER
);

ALTER TABLE location_show ADD CONSTRAINT location_show_pk PRIMARY KEY ( location_id );

CREATE TABLE organizer (
    organizer_id   INTEGER NOT NULL,
    name_o         VARCHAR2(100),
    fee_o          NUMBER,
    password_o     INTEGER,
    username_o     VARCHAR2(100)
);

ALTER TABLE organizer ADD CONSTRAINT organizer_pk PRIMARY KEY ( organizer_id );

CREATE TABLE show (
    show_id                      INTEGER NOT NULL,
    show_title                   VARCHAR2(100),
    show_date                    DATE,
    place_id                     INTEGER NOT NULL,
    type_show_type_id            INTEGER NOT NULL,
    status_show_status_id        INTEGER NOT NULL,
    location_show_location_id    INTEGER NOT NULL,
    tickets_tickets_id           INTEGER NOT NULL,
    organizer_organizer_id       INTEGER NOT NULL,
    distributor_distributor_id   INTEGER NOT NULL
);

CREATE UNIQUE INDEX show__idx ON
    show (
        type_show_type_id
    ASC );

CREATE UNIQUE INDEX show__idxv1 ON
    show (
        status_show_status_id
    ASC );

CREATE UNIQUE INDEX show__idxv2 ON
    show (
        location_show_location_id
    ASC );

ALTER TABLE show ADD CONSTRAINT show_pk PRIMARY KEY ( show_id );

CREATE TABLE status_show (
    status_id   INTEGER NOT NULL,
    status      VARCHAR2(100)
);

ALTER TABLE status_show ADD CONSTRAINT status_show_pk PRIMARY KEY ( status_id );

CREATE TABLE tickets (
    tickets_id       INTEGER NOT NULL,
    avelable         INTEGER,
    normal_tickets   INTEGER,
    vip_tickets      INTEGER
);

ALTER TABLE tickets ADD CONSTRAINT tickets_pk PRIMARY KEY ( tickets_id );

CREATE TABLE type_show (
    type_id   INTEGER NOT NULL,
    type      VARCHAR2(100)
);

ALTER TABLE type_show ADD CONSTRAINT type_show_pk PRIMARY KEY ( type_id );

ALTER TABLE form
    ADD CONSTRAINT form_customer_fk FOREIGN KEY ( customer_customer_id )
        REFERENCES customer ( customer_id );

ALTER TABLE form
    ADD CONSTRAINT form_distributor_fk FOREIGN KEY ( distributor_distributor_id )
        REFERENCES distributor ( distributor_id );

ALTER TABLE form
    ADD CONSTRAINT form_show_fk FOREIGN KEY ( show_show_id )
        REFERENCES show ( show_id );

ALTER TABLE show
    ADD CONSTRAINT show_distributor_fk FOREIGN KEY ( distributor_distributor_id )
        REFERENCES distributor ( distributor_id );

ALTER TABLE show
    ADD CONSTRAINT show_location_show_fk FOREIGN KEY ( location_show_location_id )
        REFERENCES location_show ( location_id );

ALTER TABLE show
    ADD CONSTRAINT show_organizer_fk FOREIGN KEY ( organizer_organizer_id )
        REFERENCES organizer ( organizer_id );

ALTER TABLE show
    ADD CONSTRAINT show_status_show_fk FOREIGN KEY ( status_show_status_id )
        REFERENCES status_show ( status_id );

ALTER TABLE show
    ADD CONSTRAINT show_tickets_fk FOREIGN KEY ( tickets_tickets_id )
        REFERENCES tickets ( tickets_id );

ALTER TABLE show
    ADD CONSTRAINT show_type_show_fk FOREIGN KEY ( type_show_type_id )
        REFERENCES type_show ( type_id );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             9
-- CREATE INDEX                             3
-- ALTER TABLE                             17
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
